# .goreleaser.yml
project_name: jg-cursor-cracker

before:
  hooks:
    # 确保在项目根目录执行go mod tidy，忽略data目录中的go文件
    - cd $(pwd) && go mod tidy

builds:
  - id: jg-cursor-cracker
    main: main.go
    binary: jg-cursor-cracker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Windows特殊处理
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/cursor-home/JG-Cursor-cracker/cmd.Version={{.Version}}
      - -X github.com/cursor-home/JG-Cursor-cracker/cmd.Commit={{.Commit}}
      - -X github.com/cursor-home/JG-Cursor-cracker/cmd.Date={{.Date}}
    
archives:
  - id: jg-cursor-cracker
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - TODO.md
      - img/**/*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      
release:
  github:
    owner: cursor-home
    name: JG-Cursor-cracker
  prerelease: auto
  draft: false
  name_template: "v{{.Version}}" 