name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置Go环境
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
        
    - name: 安装依赖
      run: go mod download
    
    - name: 运行测试
      run: go test -v ./pkg/cracker/... 