name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: 安装Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: 安装asar工具
        run: npm install -g asar

      - name: 设置Go环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: 运行测试
        run: go test -v ./pkg/cracker/...

      - name: 使用GoReleaser发布
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 